Tempo: 96 BPM
Metrica: 4/4

Pattern %ShuffleGtr:
  8T: 100@ [e*3 a*3] r [e*3 a*3] r [e*3 a*3] r [e*3 a*3] r

Pattern %ShuffleGtrIV:
  8T: 100@ [a*3 d*4] r [a*3 d*4] r [a*3 d*4] r [a*3 d*4] r

Pattern %ShuffleGtrV:
  8T: 100@ [b*3 e*4] r [b*3 e*4] r [b*3 e*4] r [b*3 e*4] r

Pattern %WalkBassI:
  8T: 90@ e*2 r g#*2 r a*2 r b*2 r

Pattern %WalkBassIV:
  8T: 90@ a*2 r c*3 r d*3 r e*3 r

Pattern %WalkBassV:
  8T: 90@ b*2 r d#*3 r e*3 r f#*3 r

Pattern %ShuffleDrums:
  8T: 90@ [kick hihat] hihat [snare hihat] hihat 70@ [kick hihat] hihat [snare hihat] hihat

Guitar 1:
  %ShuffleGtr %ShuffleGtr %ShuffleGtr %ShuffleGtr %ShuffleGtrIV %ShuffleGtrIV %ShuffleGtr %ShuffleGtr %ShuffleGtrV %ShuffleGtrIV %ShuffleGtr %ShuffleGtr

Bass:
  %WalkBassI %WalkBassI %WalkBassI %WalkBassI %WalkBassIV %WalkBassIV %WalkBassI %WalkBassI %WalkBassV %WalkBassIV %WalkBassI %WalkBassI

Piano:
  16: 80@ E7 r r r r r r r E7 r r r r r r r 16: A7 r r r r r r r E7 r r r r r r r 16: B7 r r r r A7 r r r r r r E7 r r r r

Drums:
  %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums %ShuffleDrums
