Tempo: 132 BPM
Metrica: 4/4

Pattern %WalkII:
  8T: 90@ d*2 f*2 a*2 c*3

Pattern %WalkV:
  8T: 90@ g*2 b*2 d*3 f*3

Pattern %WalkI:
  8T: 90@ c*2 e*2 g*2 b*2

Pattern %WalkVI:
  8T: 90@ a*2 c*3 e*3 g*3

Pattern %SwingRide:
  8T: 90@ ride r ride ride r ride ride r

Pattern %CompII:
  4: 70@ Dm7

Pattern %CompV:
  4: 70@ G7

Pattern %CompI:
  4: 70@ Cmaj7

Pattern %CompVI:
  4: 70@ Am7

Bass:
  %WalkII %WalkV %WalkI %WalkVI
  %WalkII %WalkV %WalkI %WalkI

Piano:
  %CompII %CompV %CompI %CompVI
  %CompII %CompV %CompI %CompI

Drums:
  %SwingRide %SwingRide %SwingRide %SwingRide
  %SwingRide %SwingRide %SwingRide %SwingRide
