Tempo: 168 BPM
Metrica: 4/4

Pattern %BoogieBass:
  8: 100@ c/2 e/2 g/2 a/2 c/2 e/2 a/2 g/2

Pattern %BoogieBassIV:
  8: 100@ f/2 a/2 c/3 d/3 f/2 a/2 d/3 c/3

Pattern %BoogieBassV:
  8: 100@ g/2 b/2 d/3 e/3 g/2 b/2 e/3 d/3

Pattern %RockGtr:
  8: 90@ [c/4 e/4 g/4] r [c/4 e/4 g/4] r [c/4 e/4 g/4] r [c/4 e/4 g/4] r

Pattern %RockDrums:
  8: 100@ kick hihat snare hihat kick kick snare hihat

Guitar 1:
  %RockGtr %RockGtr %RockGtr %RockGtr

Bass:
  %BoogieBass %BoogieBass %BoogieBassIV %BoogieBassIV
  %BoogieBass %BoogieBassV %BoogieBassIV %BoogieBass

Piano:
  %BoogieBass/12 %BoogieBass/12 %BoogieBassIV/12 %BoogieBassIV/12
  %BoogieBass/12 %BoogieBassV/12 %BoogieBassIV/12 %BoogieBass/12

Drums:
  %RockDrums %RockDrums %RockDrums %RockDrums
  %RockDrums %RockDrums %RockDrums %RockDrums
