Tempo: 148 BPM
Metrica: 4/4

Pattern %TwistBass:
  8: 100@ g*2 g*2 b*2 b*2 c*3 c*3 d*3 d*3

Pattern %TwistGtr:
  8: 95@ [g*3 b*3 d*4] r [g*3 b*3 d*4] r [c*4 e*4 g*4] r [d*4 f#*4 a*4] r

Pattern %TwistDrums:
  8: 105@ kick hihat snare hihat kick hihat snare hihat

Bass:
  %TwistBass %TwistBass %TwistBass %TwistBass

Guitar 1:
  %TwistGtr %TwistGtr %TwistGtr %TwistGtr

Drums:
  %TwistDrums %TwistDrums %TwistDrums %TwistDrums
