Tempo: 126 BPM
Metrica: 4/4

Pattern %RevueBass:
  16: 100@ f/2 r a/2 c/3 r f/2 r r f/2 r a/2 c/3 r g/2 r r

Pattern %RevueHorns:
  16: 105@ [f/4 a/4 c/5] r r r 95@ [f/4 a/4 c/5] r r r r r r r r r r r

Pattern %RevueDrums:
  16: 105@ kick r hihat r snare r hihat kick kick r hihat r snare r hihat r

Pattern %RevueGtr:
  16: 85@ [f/3 a/3] r r [f/3 a/3] r r [f/3 a/3] r r [f/3 a/3] r r [f/3 a/3] r r

Bass:
  %RevueBass %RevueBass %RevueBass %RevueBass

Trumpet:
  %RevueHorns %RevueHorns %RevueHorns %RevueHorns

Drums:
  %RevueDrums %RevueDrums %RevueDrums %RevueDrums

Guitar 1:
  %RevueGtr %RevueGtr %RevueGtr %RevueGtr
